//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.19 at 10:05:50 AM ICT 
//


package th.co.ais.enterprisecloud.model.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for organizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="organizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="users" type="{http://enterprisecloud.ais.co.th/bot}usersType"/>
 *         &lt;element name="vms" type="{http://enterprisecloud.ais.co.th/bot}vmsType"/>
 *         &lt;element name="networkServices" type="{http://enterprisecloud.ais.co.th/bot}networkServicesType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="orderId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="3"/>
 *             &lt;maxLength value="512"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="orgVdcName" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="url" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organizationType", propOrder = {
    "users",
    "vms",
    "networkServices"
})
public class OrganizationType {

    @XmlElement(required = true)
    protected UsersType users;
    @XmlElement(required = true)
    protected VmsType vms;
    @XmlElement(required = true)
    protected NetworkServicesType networkServices;
    @XmlAttribute(name = "orderId", required = true)
    protected String orderId;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "orgVdcName", required = true)
    protected String orgVdcName;
    @XmlAttribute(name = "url", required = true)
    protected String url;

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link UsersType }
     *     
     */
    public UsersType getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersType }
     *     
     */
    public void setUsers(UsersType value) {
        this.users = value;
    }

    /**
     * Gets the value of the vms property.
     * 
     * @return
     *     possible object is
     *     {@link VmsType }
     *     
     */
    public VmsType getVms() {
        return vms;
    }

    /**
     * Sets the value of the vms property.
     * 
     * @param value
     *     allowed object is
     *     {@link VmsType }
     *     
     */
    public void setVms(VmsType value) {
        this.vms = value;
    }

    /**
     * Gets the value of the networkServices property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkServicesType }
     *     
     */
    public NetworkServicesType getNetworkServices() {
        return networkServices;
    }

    /**
     * Sets the value of the networkServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkServicesType }
     *     
     */
    public void setNetworkServices(NetworkServicesType value) {
        this.networkServices = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the orgVdcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgVdcName() {
        return orgVdcName;
    }

    /**
     * Sets the value of the orgVdcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgVdcName(String value) {
        this.orgVdcName = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

}
