//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ipScope" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="retainNetInfoAcrossDeployments" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="fenceMode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NATROUTED"/>
 *             &lt;enumeration value="BRIDGED"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationType", propOrder = {
    "ipScope"
})
public class ConfigurationType {

    @XmlElement(required = true)
    protected List<String> ipScope;
    @XmlAttribute(name = "retainNetInfoAcrossDeployments")
    protected Boolean retainNetInfoAcrossDeployments;
    @XmlAttribute(name = "fenceMode")
    protected String fenceMode;

    /**
     * Gets the value of the ipScope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipScope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpScope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIpScope() {
        if (ipScope == null) {
            ipScope = new ArrayList<String>();
        }
        return this.ipScope;
    }

    /**
     * Gets the value of the retainNetInfoAcrossDeployments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRetainNetInfoAcrossDeployments() {
        return retainNetInfoAcrossDeployments;
    }

    /**
     * Sets the value of the retainNetInfoAcrossDeployments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetainNetInfoAcrossDeployments(Boolean value) {
        this.retainNetInfoAcrossDeployments = value;
    }

    /**
     * Gets the value of the fenceMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFenceMode() {
        return fenceMode;
    }

    /**
     * Sets the value of the fenceMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFenceMode(String value) {
        this.fenceMode = value;
    }

}
