//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EdgeGatewayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EdgeGatewayType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="gatewayConfiguration" type="{http://enterprisecloud.ais.co.th/bot}GatewayConfigurationType"/>
 *         &lt;element name="gatewayFeatures" type="{http://enterprisecloud.ais.co.th/bot}GatewayFeaturesType"/>
 *       &lt;/all>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EdgeGatewayType", propOrder = {

})
public class EdgeGatewayType {

    @XmlElement(required = true)
    protected GatewayConfigurationType gatewayConfiguration;
    @XmlElement(required = true)
    protected GatewayFeaturesType gatewayFeatures;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;

    /**
     * Gets the value of the gatewayConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link GatewayConfigurationType }
     *     
     */
    public GatewayConfigurationType getGatewayConfiguration() {
        return gatewayConfiguration;
    }

    /**
     * Sets the value of the gatewayConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link GatewayConfigurationType }
     *     
     */
    public void setGatewayConfiguration(GatewayConfigurationType value) {
        this.gatewayConfiguration = value;
    }

    /**
     * Gets the value of the gatewayFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link GatewayFeaturesType }
     *     
     */
    public GatewayFeaturesType getGatewayFeatures() {
        return gatewayFeatures;
    }

    /**
     * Sets the value of the gatewayFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link GatewayFeaturesType }
     *     
     */
    public void setGatewayFeatures(GatewayFeaturesType value) {
        this.gatewayFeatures = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
