//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GatewayInterfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GatewayInterfaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="interfaceType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="UPLINK"/>
 *               &lt;enumeration value="INTERNAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subnetParticipation" type="{http://enterprisecloud.ais.co.th/bot}SubnetParticipationType"/>
 *       &lt;/all>
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useForDefaultRoute" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GatewayInterfaceType", propOrder = {

})
public class GatewayInterfaceType {

    @XmlElement(required = true)
    protected String interfaceType;
    @XmlElement(required = true)
    protected SubnetParticipationType subnetParticipation;
    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "useForDefaultRoute")
    protected Boolean useForDefaultRoute;

    /**
     * Gets the value of the interfaceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * Sets the value of the interfaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceType(String value) {
        this.interfaceType = value;
    }

    /**
     * Gets the value of the subnetParticipation property.
     * 
     * @return
     *     possible object is
     *     {@link SubnetParticipationType }
     *     
     */
    public SubnetParticipationType getSubnetParticipation() {
        return subnetParticipation;
    }

    /**
     * Sets the value of the subnetParticipation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubnetParticipationType }
     *     
     */
    public void setSubnetParticipation(SubnetParticipationType value) {
        this.subnetParticipation = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the useForDefaultRoute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseForDefaultRoute() {
        return useForDefaultRoute;
    }

    /**
     * Sets the value of the useForDefaultRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseForDefaultRoute(Boolean value) {
        this.useForDefaultRoute = value;
    }

}
