//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GatewayConfigurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GatewayConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gatewayInterface" type="{http://enterprisecloud.ais.co.th/bot}GatewayInterfaceType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="haEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="useDefaultRouteForDnsRelay" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="gatewayBackingConfig">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="COMPACT"/>
 *             &lt;enumeration value="FULL"/>
 *             &lt;enumeration value="FULL4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GatewayConfigurationType", propOrder = {
    "gatewayInterface"
})
public class GatewayConfigurationType {

    @XmlElement(required = true)
    protected List<GatewayInterfaceType> gatewayInterface;
    @XmlAttribute(name = "haEnabled")
    protected Boolean haEnabled;
    @XmlAttribute(name = "useDefaultRouteForDnsRelay")
    protected Boolean useDefaultRouteForDnsRelay;
    @XmlAttribute(name = "gatewayBackingConfig")
    protected String gatewayBackingConfig;

    /**
     * Gets the value of the gatewayInterface property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gatewayInterface property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGatewayInterface().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GatewayInterfaceType }
     * 
     * 
     */
    public List<GatewayInterfaceType> getGatewayInterface() {
        if (gatewayInterface == null) {
            gatewayInterface = new ArrayList<GatewayInterfaceType>();
        }
        return this.gatewayInterface;
    }

    /**
     * Gets the value of the haEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHaEnabled() {
        return haEnabled;
    }

    /**
     * Sets the value of the haEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHaEnabled(Boolean value) {
        this.haEnabled = value;
    }

    /**
     * Gets the value of the useDefaultRouteForDnsRelay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseDefaultRouteForDnsRelay() {
        return useDefaultRouteForDnsRelay;
    }

    /**
     * Sets the value of the useDefaultRouteForDnsRelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseDefaultRouteForDnsRelay(Boolean value) {
        this.useDefaultRouteForDnsRelay = value;
    }

    /**
     * Gets the value of the gatewayBackingConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayBackingConfig() {
        return gatewayBackingConfig;
    }

    /**
     * Sets the value of the gatewayBackingConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayBackingConfig(String value) {
        this.gatewayBackingConfig = value;
    }

}
