//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrganizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="orgSettings" type="{http://enterprisecloud.ais.co.th/bot}OrgSettingsType" minOccurs="0"/>
 *         &lt;element name="users" type="{http://enterprisecloud.ais.co.th/bot}UsersType"/>
 *         &lt;element name="vdc" type="{http://enterprisecloud.ais.co.th/bot}VdcType" minOccurs="0"/>
 *         &lt;element name="cloudResources" type="{http://enterprisecloud.ais.co.th/bot}CloudResourcesType" minOccurs="0"/>
 *         &lt;element name="edgeGateway" type="{http://enterprisecloud.ais.co.th/bot}EdgeGatewayType" minOccurs="0"/>
 *         &lt;element name="orgVdcNetwork" type="{http://enterprisecloud.ais.co.th/bot}OrgVdcNetworkType" minOccurs="0"/>
 *         &lt;element name="vApp" type="{http://enterprisecloud.ais.co.th/bot}VAppType"/>
 *       &lt;/all>
 *       &lt;attribute name="orderId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="3"/>
 *             &lt;maxLength value="512"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orderType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="trial"/>
 *             &lt;enumeration value="standard"/>
 *             &lt;enumeration value="customize"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="caNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shortName" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="3"/>
 *             &lt;maxLength value="64"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace="http://enterprisecloud.ais.co.th/bot")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationType", propOrder = {

})
public class OrganizationType {

    protected OrgSettingsType orgSettings;
    @XmlElement(required = true)
    protected UsersType users;
    protected VdcType vdc;
    protected CloudResourcesType cloudResources;
    protected EdgeGatewayType edgeGateway;
    protected OrgVdcNetworkType orgVdcNetwork;
    @XmlElement(required = true)
    protected VAppType vApp;
    @XmlAttribute(name = "orderId", required = true)
    protected String orderId;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "orderType", required = true)
    protected String orderType;
    @XmlAttribute(name = "caNumber")
    protected String caNumber;
    @XmlAttribute(name = "shortName", required = true)
    protected String shortName;
    @XmlAttribute(name = "url")
    protected String url;

    /**
     * Gets the value of the orgSettings property.
     * 
     * @return
     *     possible object is
     *     {@link OrgSettingsType }
     *     
     */
    public OrgSettingsType getOrgSettings() {
        return orgSettings;
    }

    /**
     * Sets the value of the orgSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgSettingsType }
     *     
     */
    public void setOrgSettings(OrgSettingsType value) {
        this.orgSettings = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link UsersType }
     *     
     */
    public UsersType getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersType }
     *     
     */
    public void setUsers(UsersType value) {
        this.users = value;
    }

    /**
     * Gets the value of the vdc property.
     * 
     * @return
     *     possible object is
     *     {@link VdcType }
     *     
     */
    public VdcType getVdc() {
        return vdc;
    }

    /**
     * Sets the value of the vdc property.
     * 
     * @param value
     *     allowed object is
     *     {@link VdcType }
     *     
     */
    public void setVdc(VdcType value) {
        this.vdc = value;
    }

    /**
     * Gets the value of the cloudResources property.
     * 
     * @return
     *     possible object is
     *     {@link CloudResourcesType }
     *     
     */
    public CloudResourcesType getCloudResources() {
        return cloudResources;
    }

    /**
     * Sets the value of the cloudResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloudResourcesType }
     *     
     */
    public void setCloudResources(CloudResourcesType value) {
        this.cloudResources = value;
    }

    /**
     * Gets the value of the edgeGateway property.
     * 
     * @return
     *     possible object is
     *     {@link EdgeGatewayType }
     *     
     */
    public EdgeGatewayType getEdgeGateway() {
        return edgeGateway;
    }

    /**
     * Sets the value of the edgeGateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdgeGatewayType }
     *     
     */
    public void setEdgeGateway(EdgeGatewayType value) {
        this.edgeGateway = value;
    }

    /**
     * Gets the value of the orgVdcNetwork property.
     * 
     * @return
     *     possible object is
     *     {@link OrgVdcNetworkType }
     *     
     */
    public OrgVdcNetworkType getOrgVdcNetwork() {
        return orgVdcNetwork;
    }

    /**
     * Sets the value of the orgVdcNetwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgVdcNetworkType }
     *     
     */
    public void setOrgVdcNetwork(OrgVdcNetworkType value) {
        this.orgVdcNetwork = value;
    }

    /**
     * Gets the value of the vApp property.
     * 
     * @return
     *     possible object is
     *     {@link VAppType }
     *     
     */
    public VAppType getVApp() {
        return vApp;
    }

    /**
     * Sets the value of the vApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link VAppType }
     *     
     */
    public void setVApp(VAppType value) {
        this.vApp = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the caNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaNumber() {
        return caNumber;
    }

    /**
     * Sets the value of the caNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaNumber(String value) {
        this.caNumber = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

}
