//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrgLeaseSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgLeaseSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="deleteOnStorageLeaseExpiration" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="deploymentLeaseSeconds" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="storageLeaseSeconds" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgLeaseSettingsType")
public class OrgLeaseSettingsType {

    @XmlAttribute(name = "deleteOnStorageLeaseExpiration")
    protected Boolean deleteOnStorageLeaseExpiration;
    @XmlAttribute(name = "deploymentLeaseSeconds")
    protected Integer deploymentLeaseSeconds;
    @XmlAttribute(name = "storageLeaseSeconds")
    protected Integer storageLeaseSeconds;

    /**
     * Gets the value of the deleteOnStorageLeaseExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeleteOnStorageLeaseExpiration() {
        return deleteOnStorageLeaseExpiration;
    }

    /**
     * Sets the value of the deleteOnStorageLeaseExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleteOnStorageLeaseExpiration(Boolean value) {
        this.deleteOnStorageLeaseExpiration = value;
    }

    /**
     * Gets the value of the deploymentLeaseSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeploymentLeaseSeconds() {
        return deploymentLeaseSeconds;
    }

    /**
     * Sets the value of the deploymentLeaseSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeploymentLeaseSeconds(Integer value) {
        this.deploymentLeaseSeconds = value;
    }

    /**
     * Gets the value of the storageLeaseSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStorageLeaseSeconds() {
        return storageLeaseSeconds;
    }

    /**
     * Sets the value of the storageLeaseSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStorageLeaseSeconds(Integer value) {
        this.storageLeaseSeconds = value;
    }

}
