//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrgSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="orgLeaseSettings" type="{http://enterprisecloud.ais.co.th/bot}OrgLeaseSettingsType" minOccurs="0"/>
 *         &lt;element name="orgGeneralSettings" type="{http://enterprisecloud.ais.co.th/bot}OrgGeneralSettingsType" minOccurs="0"/>
 *         &lt;element name="orgVAppTemplateLeaseSettings" type="{http://enterprisecloud.ais.co.th/bot}OrgVAppTemplateLeaseSettingsType" minOccurs="0"/>
 *         &lt;element name="orgPasswordPolicySettings" type="{http://enterprisecloud.ais.co.th/bot}OrgPasswordPolicySettingsType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgSettingsType", propOrder = {

})
public class OrgSettingsType {

    protected OrgLeaseSettingsType orgLeaseSettings;
    protected OrgGeneralSettingsType orgGeneralSettings;
    protected OrgVAppTemplateLeaseSettingsType orgVAppTemplateLeaseSettings;
    protected OrgPasswordPolicySettingsType orgPasswordPolicySettings;

    /**
     * Gets the value of the orgLeaseSettings property.
     * 
     * @return
     *     possible object is
     *     {@link OrgLeaseSettingsType }
     *     
     */
    public OrgLeaseSettingsType getOrgLeaseSettings() {
        return orgLeaseSettings;
    }

    /**
     * Sets the value of the orgLeaseSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgLeaseSettingsType }
     *     
     */
    public void setOrgLeaseSettings(OrgLeaseSettingsType value) {
        this.orgLeaseSettings = value;
    }

    /**
     * Gets the value of the orgGeneralSettings property.
     * 
     * @return
     *     possible object is
     *     {@link OrgGeneralSettingsType }
     *     
     */
    public OrgGeneralSettingsType getOrgGeneralSettings() {
        return orgGeneralSettings;
    }

    /**
     * Sets the value of the orgGeneralSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgGeneralSettingsType }
     *     
     */
    public void setOrgGeneralSettings(OrgGeneralSettingsType value) {
        this.orgGeneralSettings = value;
    }

    /**
     * Gets the value of the orgVAppTemplateLeaseSettings property.
     * 
     * @return
     *     possible object is
     *     {@link OrgVAppTemplateLeaseSettingsType }
     *     
     */
    public OrgVAppTemplateLeaseSettingsType getOrgVAppTemplateLeaseSettings() {
        return orgVAppTemplateLeaseSettings;
    }

    /**
     * Sets the value of the orgVAppTemplateLeaseSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgVAppTemplateLeaseSettingsType }
     *     
     */
    public void setOrgVAppTemplateLeaseSettings(OrgVAppTemplateLeaseSettingsType value) {
        this.orgVAppTemplateLeaseSettings = value;
    }

    /**
     * Gets the value of the orgPasswordPolicySettings property.
     * 
     * @return
     *     possible object is
     *     {@link OrgPasswordPolicySettingsType }
     *     
     */
    public OrgPasswordPolicySettingsType getOrgPasswordPolicySettings() {
        return orgPasswordPolicySettings;
    }

    /**
     * Sets the value of the orgPasswordPolicySettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgPasswordPolicySettingsType }
     *     
     */
    public void setOrgPasswordPolicySettings(OrgPasswordPolicySettingsType value) {
        this.orgPasswordPolicySettings = value;
    }

}
