//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VdcType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VdcType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="computeCapacity" type="{http://enterprisecloud.ais.co.th/bot}ComputeCapacityType" minOccurs="0"/>
 *         &lt;element name="vdcStorageProfile" type="{http://enterprisecloud.ais.co.th/bot}VdcStorageProfileType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="resourceGuaranteedCpu" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="resourceGuaranteedMemory" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="vmQuota" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="networkQuota" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VdcType", propOrder = {

})
public class VdcType {

    protected ComputeCapacityType computeCapacity;
    protected VdcStorageProfileType vdcStorageProfile;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;
    @XmlAttribute(name = "resourceGuaranteedCpu")
    protected Float resourceGuaranteedCpu;
    @XmlAttribute(name = "resourceGuaranteedMemory")
    protected Float resourceGuaranteedMemory;
    @XmlAttribute(name = "vmQuota")
    protected Integer vmQuota;
    @XmlAttribute(name = "networkQuota")
    protected Integer networkQuota;

    /**
     * Gets the value of the computeCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link ComputeCapacityType }
     *     
     */
    public ComputeCapacityType getComputeCapacity() {
        return computeCapacity;
    }

    /**
     * Sets the value of the computeCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComputeCapacityType }
     *     
     */
    public void setComputeCapacity(ComputeCapacityType value) {
        this.computeCapacity = value;
    }

    /**
     * Gets the value of the vdcStorageProfile property.
     * 
     * @return
     *     possible object is
     *     {@link VdcStorageProfileType }
     *     
     */
    public VdcStorageProfileType getVdcStorageProfile() {
        return vdcStorageProfile;
    }

    /**
     * Sets the value of the vdcStorageProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link VdcStorageProfileType }
     *     
     */
    public void setVdcStorageProfile(VdcStorageProfileType value) {
        this.vdcStorageProfile = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the resourceGuaranteedCpu property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getResourceGuaranteedCpu() {
        return resourceGuaranteedCpu;
    }

    /**
     * Sets the value of the resourceGuaranteedCpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setResourceGuaranteedCpu(Float value) {
        this.resourceGuaranteedCpu = value;
    }

    /**
     * Gets the value of the resourceGuaranteedMemory property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getResourceGuaranteedMemory() {
        return resourceGuaranteedMemory;
    }

    /**
     * Sets the value of the resourceGuaranteedMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setResourceGuaranteedMemory(Float value) {
        this.resourceGuaranteedMemory = value;
    }

    /**
     * Gets the value of the vmQuota property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVmQuota() {
        return vmQuota;
    }

    /**
     * Sets the value of the vmQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVmQuota(Integer value) {
        this.vmQuota = value;
    }

    /**
     * Gets the value of the networkQuota property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetworkQuota() {
        return networkQuota;
    }

    /**
     * Sets the value of the networkQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetworkQuota(Integer value) {
        this.networkQuota = value;
    }

}
