//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.nontster.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Organization_QNAME = new QName("http://enterprisecloud.ais.co.th/bot", "organization");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.nontster.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link VmsType }
     * 
     */
    public VmsType createVmsType() {
        return new VmsType();
    }

    /**
     * Create an instance of {@link EdgeGatewayType }
     * 
     */
    public EdgeGatewayType createEdgeGatewayType() {
        return new EdgeGatewayType();
    }

    /**
     * Create an instance of {@link OrgLeaseSettingsType }
     * 
     */
    public OrgLeaseSettingsType createOrgLeaseSettingsType() {
        return new OrgLeaseSettingsType();
    }

    /**
     * Create an instance of {@link VAppType }
     * 
     */
    public VAppType createVAppType() {
        return new VAppType();
    }

    /**
     * Create an instance of {@link SubnetParticipationType }
     * 
     */
    public SubnetParticipationType createSubnetParticipationType() {
        return new SubnetParticipationType();
    }

    /**
     * Create an instance of {@link FirewallServiceType }
     * 
     */
    public FirewallServiceType createFirewallServiceType() {
        return new FirewallServiceType();
    }

    /**
     * Create an instance of {@link VmType }
     * 
     */
    public VmType createVmType() {
        return new VmType();
    }

    /**
     * Create an instance of {@link CpuType }
     * 
     */
    public CpuType createCpuType() {
        return new CpuType();
    }

    /**
     * Create an instance of {@link ProviderVdcType }
     * 
     */
    public ProviderVdcType createProviderVdcType() {
        return new ProviderVdcType();
    }

    /**
     * Create an instance of {@link NetworkPoolType }
     * 
     */
    public NetworkPoolType createNetworkPoolType() {
        return new NetworkPoolType();
    }

    /**
     * Create an instance of {@link MemoryType }
     * 
     */
    public MemoryType createMemoryType() {
        return new MemoryType();
    }

    /**
     * Create an instance of {@link ConfigurationType }
     * 
     */
    public ConfigurationType createConfigurationType() {
        return new ConfigurationType();
    }

    /**
     * Create an instance of {@link OrgGeneralSettingsType }
     * 
     */
    public OrgGeneralSettingsType createOrgGeneralSettingsType() {
        return new OrgGeneralSettingsType();
    }

    /**
     * Create an instance of {@link CloudResourcesType }
     * 
     */
    public CloudResourcesType createCloudResourcesType() {
        return new CloudResourcesType();
    }

    /**
     * Create an instance of {@link FirewallRulesType }
     * 
     */
    public FirewallRulesType createFirewallRulesType() {
        return new FirewallRulesType();
    }

    /**
     * Create an instance of {@link OrgPasswordPolicySettingsType }
     * 
     */
    public OrgPasswordPolicySettingsType createOrgPasswordPolicySettingsType() {
        return new OrgPasswordPolicySettingsType();
    }

    /**
     * Create an instance of {@link OrgVAppTemplateLeaseSettingsType }
     * 
     */
    public OrgVAppTemplateLeaseSettingsType createOrgVAppTemplateLeaseSettingsType() {
        return new OrgVAppTemplateLeaseSettingsType();
    }

    /**
     * Create an instance of {@link CatalogType }
     * 
     */
    public CatalogType createCatalogType() {
        return new CatalogType();
    }

    /**
     * Create an instance of {@link VdcStorageProfileType }
     * 
     */
    public VdcStorageProfileType createVdcStorageProfileType() {
        return new VdcStorageProfileType();
    }

    /**
     * Create an instance of {@link GatewayConfigurationType }
     * 
     */
    public GatewayConfigurationType createGatewayConfigurationType() {
        return new GatewayConfigurationType();
    }

    /**
     * Create an instance of {@link IpRangesType }
     * 
     */
    public IpRangesType createIpRangesType() {
        return new IpRangesType();
    }

    /**
     * Create an instance of {@link OrgSettingsType }
     * 
     */
    public OrgSettingsType createOrgSettingsType() {
        return new OrgSettingsType();
    }

    /**
     * Create an instance of {@link ExternalNetworkType }
     * 
     */
    public ExternalNetworkType createExternalNetworkType() {
        return new ExternalNetworkType();
    }

    /**
     * Create an instance of {@link GatewayFeaturesType }
     * 
     */
    public GatewayFeaturesType createGatewayFeaturesType() {
        return new GatewayFeaturesType();
    }

    /**
     * Create an instance of {@link UsersType }
     * 
     */
    public UsersType createUsersType() {
        return new UsersType();
    }

    /**
     * Create an instance of {@link VdcType }
     * 
     */
    public VdcType createVdcType() {
        return new VdcType();
    }

    /**
     * Create an instance of {@link GatewayInterfaceType }
     * 
     */
    public GatewayInterfaceType createGatewayInterfaceType() {
        return new GatewayInterfaceType();
    }

    /**
     * Create an instance of {@link ComputeCapacityType }
     * 
     */
    public ComputeCapacityType createComputeCapacityType() {
        return new ComputeCapacityType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link OrgVdcNetworkType }
     * 
     */
    public OrgVdcNetworkType createOrgVdcNetworkType() {
        return new OrgVdcNetworkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprisecloud.ais.co.th/bot", name = "organization")
    public JAXBElement<OrganizationType> createOrganization(OrganizationType value) {
        return new JAXBElement<OrganizationType>(_Organization_QNAME, OrganizationType.class, null, value);
    }

}
