//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrgGeneralSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgGeneralSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="storedVmQuota" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="deployedVMQuota" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="canPublishCatalogs" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgGeneralSettingsType")
public class OrgGeneralSettingsType {

    @XmlAttribute(name = "storedVmQuota")
    protected Integer storedVmQuota;
    @XmlAttribute(name = "deployedVMQuota")
    protected Integer deployedVMQuota;
    @XmlAttribute(name = "canPublishCatalogs")
    protected Boolean canPublishCatalogs;

    /**
     * Gets the value of the storedVmQuota property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStoredVmQuota() {
        return storedVmQuota;
    }

    /**
     * Sets the value of the storedVmQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStoredVmQuota(Integer value) {
        this.storedVmQuota = value;
    }

    /**
     * Gets the value of the deployedVMQuota property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeployedVMQuota() {
        return deployedVMQuota;
    }

    /**
     * Sets the value of the deployedVMQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeployedVMQuota(Integer value) {
        this.deployedVMQuota = value;
    }

    /**
     * Gets the value of the canPublishCatalogs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanPublishCatalogs() {
        return canPublishCatalogs;
    }

    /**
     * Sets the value of the canPublishCatalogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanPublishCatalogs(Boolean value) {
        this.canPublishCatalogs = value;
    }

}
