//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:44:53 PM ICT 
//


package th.co.ais.enterprisecloud.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrgPasswordPolicySettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgPasswordPolicySettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="accountLockoutEnabled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accountLockoutIntervalMinutes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="invalidLoginsBeforeLockout" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgPasswordPolicySettingsType")
public class OrgPasswordPolicySettingsType {

    @XmlAttribute(name = "accountLockoutEnabled")
    protected String accountLockoutEnabled;
    @XmlAttribute(name = "accountLockoutIntervalMinutes")
    protected String accountLockoutIntervalMinutes;
    @XmlAttribute(name = "invalidLoginsBeforeLockout")
    protected String invalidLoginsBeforeLockout;

    /**
     * Gets the value of the accountLockoutEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountLockoutEnabled() {
        return accountLockoutEnabled;
    }

    /**
     * Sets the value of the accountLockoutEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountLockoutEnabled(String value) {
        this.accountLockoutEnabled = value;
    }

    /**
     * Gets the value of the accountLockoutIntervalMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountLockoutIntervalMinutes() {
        return accountLockoutIntervalMinutes;
    }

    /**
     * Sets the value of the accountLockoutIntervalMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountLockoutIntervalMinutes(String value) {
        this.accountLockoutIntervalMinutes = value;
    }

    /**
     * Gets the value of the invalidLoginsBeforeLockout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvalidLoginsBeforeLockout() {
        return invalidLoginsBeforeLockout;
    }

    /**
     * Sets the value of the invalidLoginsBeforeLockout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvalidLoginsBeforeLockout(String value) {
        this.invalidLoginsBeforeLockout = value;
    }

}
