//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.29 at 01:39:40 PM ICT 
//


package th.co.ais.enterprisecloud.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for networkServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="networkServicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firewallService" type="{http://enterprisecloud.ais.co.th/bot}firewallServiceType"/>
 *         &lt;element name="natService" type="{http://enterprisecloud.ais.co.th/bot}natServiceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "networkServicesType", propOrder = {
    "firewallService",
    "natService"
})
public class NetworkServicesType {

    @XmlElement(required = true)
    protected FirewallServiceType firewallService;
    @XmlElement(required = true)
    protected NatServiceType natService;

    /**
     * Gets the value of the firewallService property.
     * 
     * @return
     *     possible object is
     *     {@link FirewallServiceType }
     *     
     */
    public FirewallServiceType getFirewallService() {
        return firewallService;
    }

    /**
     * Sets the value of the firewallService property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirewallServiceType }
     *     
     */
    public void setFirewallService(FirewallServiceType value) {
        this.firewallService = value;
    }

    /**
     * Gets the value of the natService property.
     * 
     * @return
     *     possible object is
     *     {@link NatServiceType }
     *     
     */
    public NatServiceType getNatService() {
        return natService;
    }

    /**
     * Sets the value of the natService property.
     * 
     * @param value
     *     allowed object is
     *     {@link NatServiceType }
     *     
     */
    public void setNatService(NatServiceType value) {
        this.natService = value;
    }

}
